---

- name: Create config directory
  ansible.builtin.file:
    path: "{{ ansible_user_configdir }}/komga"
    state: directory

- name: Start Komga Service
  containers.podman.podman_container:
    name: "komga"
    image: docker.io/gotson/komga:latest
    state: started
    recreate: true
    user: root
    ports:
      - "8080:8080"
    volume:
      - "{{ ansible_user_configdir }}/komga:/config:Z"
      - "{{ media_share }}/Reading:/data:ro"
    env:
      TZ: America/Detroit
