---

- name: Minecraft Server
  hosts: container_host

  vars:
    app_name: minecraft

  tasks:
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ ansible_user_configdir }}/{{ app_name }}"
        state: directory
    
    - name: Start {{ app_name }} service
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: docker.io/itzg/minecraft-server:latest
        state: started
        user: root
        ports:
          - "25565:25565"
        volume:
          - "{{ ansible_user_configdir }}/{{ app_name }}:/data:Z"
        env:
          TZ: America/Detroit
          EULA: "TRUE"
