---

- name: Create config directory
  ansible.builtin.file:
    path: "{{ ansible_user_configdir }}/navidrome"
    state: directory

- name: Start Navidrome service
  containers.podman.podman_container:
    name: "navidrome"
    image: docker.io/deluan/navidrome:latest
    state: started
    recreate: true
    user: root
    ports:
      - "4533:4533"
    volume:
      - "{{ ansible_user_configdir }}/navidrome:/data:Z"
      - "{{ media_share }}/Media/Music:/music:ro"
    env:
      TZ: America/Detroit
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_ENABLECOVERANIMATION: true
      ND_ENABLEDOWNLOADS: true
      ND_LASTFM_ENABLED: true
      ND_LISTENBRAINZ_ENABLED: true
      ND_COVERJPEGQUALITY: 90
